package com.xin.data.model;

import java.math.BigDecimal;
import java.util.Date;

public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.id
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.code
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.name
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.category
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private Integer category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.level
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.source
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private Integer source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.pay_type_id
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private Long payTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.payment_type
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private Integer paymentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.type
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.market_area
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private String marketArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.industry
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private Integer industry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.postcode
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private String postcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.address
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.fax
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.telphone
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private String telphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.website
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private String website;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.remark
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.creatorid
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private Long creatorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.createtime
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.updatorid
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private Long updatorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.updatetime
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.is_delete
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private Byte isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.version
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private Long version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.last_tax_id
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private Long lastTaxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.last_tax_rate
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private BigDecimal lastTaxRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.a_id
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private Long aId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.organization_id
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private Long organizationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.taker_id
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private Long takerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.taker_name
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private String takerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.state
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.credit_state
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private Byte creditState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.credit_amount
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private BigDecimal creditAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.currency_id
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private Long currencyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.taker_organization_id
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private Long takerOrganizationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.continent_id
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private Long continentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.country_id
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private Long countryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.region_id
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private Long regionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.province_id
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private Long provinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.city_id
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private Long cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.area_id
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private Long areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.is_new
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private Byte isNew;
    /**
     * 回收时间
     */
    private Date recycleTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.allot_time
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    private Date allotTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crm_customer.recycle_time
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */

    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.id
     *
     * @param id the value for crm_customer.id
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.code
     *
     * @return the value of crm_customer.code
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.code
     *
     * @param code the value for crm_customer.code
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.name
     *
     * @return the value of crm_customer.name
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.name
     *
     * @param name the value for crm_customer.name
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.category
     *
     * @return the value of crm_customer.category
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.category
     *
     * @param category the value for crm_customer.category
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.level
     *
     * @return the value of crm_customer.level
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.level
     *
     * @param level the value for crm_customer.level
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.source
     *
     * @return the value of crm_customer.source
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public Integer getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.source
     *
     * @param source the value for crm_customer.source
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setSource(Integer source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.pay_type_id
     *
     * @return the value of crm_customer.pay_type_id
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public Long getPayTypeId() {
        return payTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.pay_type_id
     *
     * @param payTypeId the value for crm_customer.pay_type_id
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setPayTypeId(Long payTypeId) {
        this.payTypeId = payTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.payment_type
     *
     * @return the value of crm_customer.payment_type
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public Integer getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.payment_type
     *
     * @param paymentType the value for crm_customer.payment_type
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setPaymentType(Integer paymentType) {
        this.paymentType = paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.type
     *
     * @return the value of crm_customer.type
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.type
     *
     * @param type the value for crm_customer.type
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.market_area
     *
     * @return the value of crm_customer.market_area
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public String getMarketArea() {
        return marketArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.market_area
     *
     * @param marketArea the value for crm_customer.market_area
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setMarketArea(String marketArea) {
        this.marketArea = marketArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.industry
     *
     * @return the value of crm_customer.industry
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public Integer getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.industry
     *
     * @param industry the value for crm_customer.industry
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setIndustry(Integer industry) {
        this.industry = industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.postcode
     *
     * @return the value of crm_customer.postcode
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.postcode
     *
     * @param postcode the value for crm_customer.postcode
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.address
     *
     * @return the value of crm_customer.address
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.address
     *
     * @param address the value for crm_customer.address
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.fax
     *
     * @return the value of crm_customer.fax
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.fax
     *
     * @param fax the value for crm_customer.fax
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setFax(String fax) {
        this.fax = fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.telphone
     *
     * @return the value of crm_customer.telphone
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.telphone
     *
     * @param telphone the value for crm_customer.telphone
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.website
     *
     * @return the value of crm_customer.website
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.website
     *
     * @param website the value for crm_customer.website
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setWebsite(String website) {
        this.website = website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.remark
     *
     * @return the value of crm_customer.remark
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.remark
     *
     * @param remark the value for crm_customer.remark
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.creatorid
     *
     * @return the value of crm_customer.creatorid
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public Long getCreatorid() {
        return creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.creatorid
     *
     * @param creatorid the value for crm_customer.creatorid
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setCreatorid(Long creatorid) {
        this.creatorid = creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.createtime
     *
     * @return the value of crm_customer.createtime
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.createtime
     *
     * @param createtime the value for crm_customer.createtime
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.updatorid
     *
     * @return the value of crm_customer.updatorid
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public Long getUpdatorid() {
        return updatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.updatorid
     *
     * @param updatorid the value for crm_customer.updatorid
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setUpdatorid(Long updatorid) {
        this.updatorid = updatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.updatetime
     *
     * @return the value of crm_customer.updatetime
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.updatetime
     *
     * @param updatetime the value for crm_customer.updatetime
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.is_delete
     *
     * @return the value of crm_customer.is_delete
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.is_delete
     *
     * @param isDelete the value for crm_customer.is_delete
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.version
     *
     * @return the value of crm_customer.version
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.version
     *
     * @param version the value for crm_customer.version
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.last_tax_id
     *
     * @return the value of crm_customer.last_tax_id
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public Long getLastTaxId() {
        return lastTaxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.last_tax_id
     *
     * @param lastTaxId the value for crm_customer.last_tax_id
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setLastTaxId(Long lastTaxId) {
        this.lastTaxId = lastTaxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.last_tax_rate
     *
     * @return the value of crm_customer.last_tax_rate
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public BigDecimal getLastTaxRate() {
        return lastTaxRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.last_tax_rate
     *
     * @param lastTaxRate the value for crm_customer.last_tax_rate
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setLastTaxRate(BigDecimal lastTaxRate) {
        this.lastTaxRate = lastTaxRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.a_id
     *
     * @return the value of crm_customer.a_id
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public Long getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.a_id
     *
     * @param aId the value for crm_customer.a_id
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setaId(Long aId) {
        this.aId = aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.organization_id
     *
     * @return the value of crm_customer.organization_id
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public Long getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.organization_id
     *
     * @param organizationId the value for crm_customer.organization_id
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setOrganizationId(Long organizationId) {
        this.organizationId = organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.taker_id
     *
     * @return the value of crm_customer.taker_id
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public Long getTakerId() {
        return takerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.taker_id
     *
     * @param takerId the value for crm_customer.taker_id
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setTakerId(Long takerId) {
        this.takerId = takerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.taker_name
     *
     * @return the value of crm_customer.taker_name
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public String getTakerName() {
        return takerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.taker_name
     *
     * @param takerName the value for crm_customer.taker_name
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setTakerName(String takerName) {
        this.takerName = takerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.state
     *
     * @return the value of crm_customer.state
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.state
     *
     * @param state the value for crm_customer.state
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.credit_state
     *
     * @return the value of crm_customer.credit_state
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public Byte getCreditState() {
        return creditState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.credit_state
     *
     * @param creditState the value for crm_customer.credit_state
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setCreditState(Byte creditState) {
        this.creditState = creditState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.credit_amount
     *
     * @return the value of crm_customer.credit_amount
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public BigDecimal getCreditAmount() {
        return creditAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.credit_amount
     *
     * @param creditAmount the value for crm_customer.credit_amount
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setCreditAmount(BigDecimal creditAmount) {
        this.creditAmount = creditAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.currency_id
     *
     * @return the value of crm_customer.currency_id
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public Long getCurrencyId() {
        return currencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.currency_id
     *
     * @param currencyId the value for crm_customer.currency_id
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setCurrencyId(Long currencyId) {
        this.currencyId = currencyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.taker_organization_id
     *
     * @return the value of crm_customer.taker_organization_id
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public Long getTakerOrganizationId() {
        return takerOrganizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.taker_organization_id
     *
     * @param takerOrganizationId the value for crm_customer.taker_organization_id
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setTakerOrganizationId(Long takerOrganizationId) {
        this.takerOrganizationId = takerOrganizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.continent_id
     *
     * @return the value of crm_customer.continent_id
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public Long getContinentId() {
        return continentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.continent_id
     *
     * @param continentId the value for crm_customer.continent_id
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setContinentId(Long continentId) {
        this.continentId = continentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.country_id
     *
     * @return the value of crm_customer.country_id
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public Long getCountryId() {
        return countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.country_id
     *
     * @param countryId the value for crm_customer.country_id
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setCountryId(Long countryId) {
        this.countryId = countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.region_id
     *
     * @return the value of crm_customer.region_id
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public Long getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.region_id
     *
     * @param regionId the value for crm_customer.region_id
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setRegionId(Long regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.province_id
     *
     * @return the value of crm_customer.province_id
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public Long getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.province_id
     *
     * @param provinceId the value for crm_customer.province_id
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setProvinceId(Long provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.city_id
     *
     * @return the value of crm_customer.city_id
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public Long getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.city_id
     *
     * @param cityId the value for crm_customer.city_id
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setCityId(Long cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.area_id
     *
     * @return the value of crm_customer.area_id
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public Long getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.area_id
     *
     * @param areaId the value for crm_customer.area_id
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setAreaId(Long areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.is_new
     *
     * @return the value of crm_customer.is_new
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public Byte getIsNew() {
        return isNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.is_new
     *
     * @param isNew the value for crm_customer.is_new
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setIsNew(Byte isNew) {
        this.isNew = isNew;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.allot_time
     *
     * @return the value of crm_customer.allot_time
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public Date getAllotTime() {
        return allotTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crm_customer.allot_time
     *
     * @param allotTime the value for crm_customer.allot_time
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */
    public void setAllotTime(Date allotTime) {
        this.allotTime = allotTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crm_customer.recycle_time
     *
     * @return the value of crm_customer.recycle_time
     *
     * @mbggenerated Wed Nov 25 15:30:33 CST 2020
     */

    public Date getRecycleTime() {
        return recycleTime;
    }

    public void setRecycleTime(Date recycleTime) {
        this.recycleTime = recycleTime;
    }
}