package com.xin.data.model;

import java.util.Date;

public class Employee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.id
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.name
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.gender
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private Byte gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.mobile
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.email
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.qq
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.birthplace
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private String birthplace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.address
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.checkin_date
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private Integer checkinDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.checkin_type
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private Byte checkinType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.birthday
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.emergency_contact_person
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private String emergencyContactPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.emergency_contact_mobile
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private String emergencyContactMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.creatorid
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private Long creatorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.createtime
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.isvalid
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private Byte isvalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.updatorid
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private Long updatorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.updatetime
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.wechat_no
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private String wechatNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.extension_number
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private String extensionNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.class_identity
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private Integer classIdentity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.native_place
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private String nativePlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.id_card_number
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private String idCardNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.social_security_number
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private String socialSecurityNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.housing_fund_number
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private String housingFundNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.social_security_type
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private Integer socialSecurityType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.wage_card_number
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private String wageCardNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.deposit_bank
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private String depositBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.age
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.level
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.organizationid
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private Long organizationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.avatar_path
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private String avatarPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.is_delete
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private Byte isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.leader
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private Long leader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.version
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private Long version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.fullname
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private String fullname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.position_name
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private String positionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.hire_date
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private String hireDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.leave_date
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private String leaveDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.is_virtual
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private Short isVirtual;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.no
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private String no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.position_id
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private Long positionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.state
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.login_name
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.pinyin_first_char
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private String pinyinFirstChar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.probation_date
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private String probationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.regular_date
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private String regularDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.separated_date
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private String separatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.rank_id
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private Long rankId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.rank_date
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private String rankDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.leader_id
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private Long leaderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.a_id
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private Long aId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.id_card_valid_date
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private String idCardValidDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.marital_state
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private Byte maritalState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.leave_reason
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private String leaveReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.ethnic_group
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private Integer ethnicGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.degree
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private Integer degree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.school_name
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private String schoolName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.major
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private String major;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.contract_start_date
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private String contractStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oa_employee.contract_end_date
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    private String contractEndDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.id
     *
     * @return the value of oa_employee.id
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.id
     *
     * @param id the value for oa_employee.id
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.name
     *
     * @return the value of oa_employee.name
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.name
     *
     * @param name the value for oa_employee.name
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.gender
     *
     * @return the value of oa_employee.gender
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.gender
     *
     * @param gender the value for oa_employee.gender
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.mobile
     *
     * @return the value of oa_employee.mobile
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.mobile
     *
     * @param mobile the value for oa_employee.mobile
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.email
     *
     * @return the value of oa_employee.email
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.email
     *
     * @param email the value for oa_employee.email
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.qq
     *
     * @return the value of oa_employee.qq
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.qq
     *
     * @param qq the value for oa_employee.qq
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.birthplace
     *
     * @return the value of oa_employee.birthplace
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public String getBirthplace() {
        return birthplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.birthplace
     *
     * @param birthplace the value for oa_employee.birthplace
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setBirthplace(String birthplace) {
        this.birthplace = birthplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.address
     *
     * @return the value of oa_employee.address
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.address
     *
     * @param address the value for oa_employee.address
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.checkin_date
     *
     * @return the value of oa_employee.checkin_date
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public Integer getCheckinDate() {
        return checkinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.checkin_date
     *
     * @param checkinDate the value for oa_employee.checkin_date
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setCheckinDate(Integer checkinDate) {
        this.checkinDate = checkinDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.checkin_type
     *
     * @return the value of oa_employee.checkin_type
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public Byte getCheckinType() {
        return checkinType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.checkin_type
     *
     * @param checkinType the value for oa_employee.checkin_type
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setCheckinType(Byte checkinType) {
        this.checkinType = checkinType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.birthday
     *
     * @return the value of oa_employee.birthday
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.birthday
     *
     * @param birthday the value for oa_employee.birthday
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.emergency_contact_person
     *
     * @return the value of oa_employee.emergency_contact_person
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public String getEmergencyContactPerson() {
        return emergencyContactPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.emergency_contact_person
     *
     * @param emergencyContactPerson the value for oa_employee.emergency_contact_person
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setEmergencyContactPerson(String emergencyContactPerson) {
        this.emergencyContactPerson = emergencyContactPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.emergency_contact_mobile
     *
     * @return the value of oa_employee.emergency_contact_mobile
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public String getEmergencyContactMobile() {
        return emergencyContactMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.emergency_contact_mobile
     *
     * @param emergencyContactMobile the value for oa_employee.emergency_contact_mobile
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setEmergencyContactMobile(String emergencyContactMobile) {
        this.emergencyContactMobile = emergencyContactMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.creatorid
     *
     * @return the value of oa_employee.creatorid
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public Long getCreatorid() {
        return creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.creatorid
     *
     * @param creatorid the value for oa_employee.creatorid
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setCreatorid(Long creatorid) {
        this.creatorid = creatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.createtime
     *
     * @return the value of oa_employee.createtime
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.createtime
     *
     * @param createtime the value for oa_employee.createtime
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.isvalid
     *
     * @return the value of oa_employee.isvalid
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public Byte getIsvalid() {
        return isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.isvalid
     *
     * @param isvalid the value for oa_employee.isvalid
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setIsvalid(Byte isvalid) {
        this.isvalid = isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.updatorid
     *
     * @return the value of oa_employee.updatorid
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public Long getUpdatorid() {
        return updatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.updatorid
     *
     * @param updatorid the value for oa_employee.updatorid
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setUpdatorid(Long updatorid) {
        this.updatorid = updatorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.updatetime
     *
     * @return the value of oa_employee.updatetime
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.updatetime
     *
     * @param updatetime the value for oa_employee.updatetime
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.wechat_no
     *
     * @return the value of oa_employee.wechat_no
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public String getWechatNo() {
        return wechatNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.wechat_no
     *
     * @param wechatNo the value for oa_employee.wechat_no
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setWechatNo(String wechatNo) {
        this.wechatNo = wechatNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.extension_number
     *
     * @return the value of oa_employee.extension_number
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public String getExtensionNumber() {
        return extensionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.extension_number
     *
     * @param extensionNumber the value for oa_employee.extension_number
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setExtensionNumber(String extensionNumber) {
        this.extensionNumber = extensionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.class_identity
     *
     * @return the value of oa_employee.class_identity
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public Integer getClassIdentity() {
        return classIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.class_identity
     *
     * @param classIdentity the value for oa_employee.class_identity
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setClassIdentity(Integer classIdentity) {
        this.classIdentity = classIdentity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.native_place
     *
     * @return the value of oa_employee.native_place
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public String getNativePlace() {
        return nativePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.native_place
     *
     * @param nativePlace the value for oa_employee.native_place
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setNativePlace(String nativePlace) {
        this.nativePlace = nativePlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.id_card_number
     *
     * @return the value of oa_employee.id_card_number
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public String getIdCardNumber() {
        return idCardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.id_card_number
     *
     * @param idCardNumber the value for oa_employee.id_card_number
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setIdCardNumber(String idCardNumber) {
        this.idCardNumber = idCardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.social_security_number
     *
     * @return the value of oa_employee.social_security_number
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public String getSocialSecurityNumber() {
        return socialSecurityNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.social_security_number
     *
     * @param socialSecurityNumber the value for oa_employee.social_security_number
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setSocialSecurityNumber(String socialSecurityNumber) {
        this.socialSecurityNumber = socialSecurityNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.housing_fund_number
     *
     * @return the value of oa_employee.housing_fund_number
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public String getHousingFundNumber() {
        return housingFundNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.housing_fund_number
     *
     * @param housingFundNumber the value for oa_employee.housing_fund_number
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setHousingFundNumber(String housingFundNumber) {
        this.housingFundNumber = housingFundNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.social_security_type
     *
     * @return the value of oa_employee.social_security_type
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public Integer getSocialSecurityType() {
        return socialSecurityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.social_security_type
     *
     * @param socialSecurityType the value for oa_employee.social_security_type
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setSocialSecurityType(Integer socialSecurityType) {
        this.socialSecurityType = socialSecurityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.wage_card_number
     *
     * @return the value of oa_employee.wage_card_number
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public String getWageCardNumber() {
        return wageCardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.wage_card_number
     *
     * @param wageCardNumber the value for oa_employee.wage_card_number
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setWageCardNumber(String wageCardNumber) {
        this.wageCardNumber = wageCardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.deposit_bank
     *
     * @return the value of oa_employee.deposit_bank
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public String getDepositBank() {
        return depositBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.deposit_bank
     *
     * @param depositBank the value for oa_employee.deposit_bank
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setDepositBank(String depositBank) {
        this.depositBank = depositBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.age
     *
     * @return the value of oa_employee.age
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.age
     *
     * @param age the value for oa_employee.age
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.level
     *
     * @return the value of oa_employee.level
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.level
     *
     * @param level the value for oa_employee.level
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.organizationid
     *
     * @return the value of oa_employee.organizationid
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public Long getOrganizationid() {
        return organizationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.organizationid
     *
     * @param organizationid the value for oa_employee.organizationid
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setOrganizationid(Long organizationid) {
        this.organizationid = organizationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.avatar_path
     *
     * @return the value of oa_employee.avatar_path
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public String getAvatarPath() {
        return avatarPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.avatar_path
     *
     * @param avatarPath the value for oa_employee.avatar_path
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setAvatarPath(String avatarPath) {
        this.avatarPath = avatarPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.is_delete
     *
     * @return the value of oa_employee.is_delete
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.is_delete
     *
     * @param isDelete the value for oa_employee.is_delete
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.leader
     *
     * @return the value of oa_employee.leader
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public Long getLeader() {
        return leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.leader
     *
     * @param leader the value for oa_employee.leader
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setLeader(Long leader) {
        this.leader = leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.version
     *
     * @return the value of oa_employee.version
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.version
     *
     * @param version the value for oa_employee.version
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.fullname
     *
     * @return the value of oa_employee.fullname
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.fullname
     *
     * @param fullname the value for oa_employee.fullname
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.position_name
     *
     * @return the value of oa_employee.position_name
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public String getPositionName() {
        return positionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.position_name
     *
     * @param positionName the value for oa_employee.position_name
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setPositionName(String positionName) {
        this.positionName = positionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.hire_date
     *
     * @return the value of oa_employee.hire_date
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public String getHireDate() {
        return hireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.hire_date
     *
     * @param hireDate the value for oa_employee.hire_date
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setHireDate(String hireDate) {
        this.hireDate = hireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.leave_date
     *
     * @return the value of oa_employee.leave_date
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public String getLeaveDate() {
        return leaveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.leave_date
     *
     * @param leaveDate the value for oa_employee.leave_date
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setLeaveDate(String leaveDate) {
        this.leaveDate = leaveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.is_virtual
     *
     * @return the value of oa_employee.is_virtual
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public Short getIsVirtual() {
        return isVirtual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.is_virtual
     *
     * @param isVirtual the value for oa_employee.is_virtual
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setIsVirtual(Short isVirtual) {
        this.isVirtual = isVirtual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.no
     *
     * @return the value of oa_employee.no
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.no
     *
     * @param no the value for oa_employee.no
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setNo(String no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.position_id
     *
     * @return the value of oa_employee.position_id
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public Long getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.position_id
     *
     * @param positionId the value for oa_employee.position_id
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setPositionId(Long positionId) {
        this.positionId = positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.state
     *
     * @return the value of oa_employee.state
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.state
     *
     * @param state the value for oa_employee.state
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.login_name
     *
     * @return the value of oa_employee.login_name
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.login_name
     *
     * @param loginName the value for oa_employee.login_name
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.pinyin_first_char
     *
     * @return the value of oa_employee.pinyin_first_char
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public String getPinyinFirstChar() {
        return pinyinFirstChar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.pinyin_first_char
     *
     * @param pinyinFirstChar the value for oa_employee.pinyin_first_char
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setPinyinFirstChar(String pinyinFirstChar) {
        this.pinyinFirstChar = pinyinFirstChar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.probation_date
     *
     * @return the value of oa_employee.probation_date
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public String getProbationDate() {
        return probationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.probation_date
     *
     * @param probationDate the value for oa_employee.probation_date
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setProbationDate(String probationDate) {
        this.probationDate = probationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.regular_date
     *
     * @return the value of oa_employee.regular_date
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public String getRegularDate() {
        return regularDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.regular_date
     *
     * @param regularDate the value for oa_employee.regular_date
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setRegularDate(String regularDate) {
        this.regularDate = regularDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.separated_date
     *
     * @return the value of oa_employee.separated_date
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public String getSeparatedDate() {
        return separatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.separated_date
     *
     * @param separatedDate the value for oa_employee.separated_date
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setSeparatedDate(String separatedDate) {
        this.separatedDate = separatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.rank_id
     *
     * @return the value of oa_employee.rank_id
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public Long getRankId() {
        return rankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.rank_id
     *
     * @param rankId the value for oa_employee.rank_id
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setRankId(Long rankId) {
        this.rankId = rankId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.rank_date
     *
     * @return the value of oa_employee.rank_date
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public String getRankDate() {
        return rankDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.rank_date
     *
     * @param rankDate the value for oa_employee.rank_date
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setRankDate(String rankDate) {
        this.rankDate = rankDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.leader_id
     *
     * @return the value of oa_employee.leader_id
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public Long getLeaderId() {
        return leaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.leader_id
     *
     * @param leaderId the value for oa_employee.leader_id
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setLeaderId(Long leaderId) {
        this.leaderId = leaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.a_id
     *
     * @return the value of oa_employee.a_id
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public Long getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.a_id
     *
     * @param aId the value for oa_employee.a_id
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setaId(Long aId) {
        this.aId = aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.id_card_valid_date
     *
     * @return the value of oa_employee.id_card_valid_date
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public String getIdCardValidDate() {
        return idCardValidDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.id_card_valid_date
     *
     * @param idCardValidDate the value for oa_employee.id_card_valid_date
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setIdCardValidDate(String idCardValidDate) {
        this.idCardValidDate = idCardValidDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.marital_state
     *
     * @return the value of oa_employee.marital_state
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public Byte getMaritalState() {
        return maritalState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.marital_state
     *
     * @param maritalState the value for oa_employee.marital_state
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setMaritalState(Byte maritalState) {
        this.maritalState = maritalState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.leave_reason
     *
     * @return the value of oa_employee.leave_reason
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public String getLeaveReason() {
        return leaveReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.leave_reason
     *
     * @param leaveReason the value for oa_employee.leave_reason
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setLeaveReason(String leaveReason) {
        this.leaveReason = leaveReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.ethnic_group
     *
     * @return the value of oa_employee.ethnic_group
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public Integer getEthnicGroup() {
        return ethnicGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.ethnic_group
     *
     * @param ethnicGroup the value for oa_employee.ethnic_group
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setEthnicGroup(Integer ethnicGroup) {
        this.ethnicGroup = ethnicGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.degree
     *
     * @return the value of oa_employee.degree
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public Integer getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.degree
     *
     * @param degree the value for oa_employee.degree
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setDegree(Integer degree) {
        this.degree = degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.school_name
     *
     * @return the value of oa_employee.school_name
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.school_name
     *
     * @param schoolName the value for oa_employee.school_name
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.major
     *
     * @return the value of oa_employee.major
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.major
     *
     * @param major the value for oa_employee.major
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setMajor(String major) {
        this.major = major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.contract_start_date
     *
     * @return the value of oa_employee.contract_start_date
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public String getContractStartDate() {
        return contractStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.contract_start_date
     *
     * @param contractStartDate the value for oa_employee.contract_start_date
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setContractStartDate(String contractStartDate) {
        this.contractStartDate = contractStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oa_employee.contract_end_date
     *
     * @return the value of oa_employee.contract_end_date
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public String getContractEndDate() {
        return contractEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oa_employee.contract_end_date
     *
     * @param contractEndDate the value for oa_employee.contract_end_date
     *
     * @mbggenerated Thu Jan 21 16:22:34 CST 2021
     */
    public void setContractEndDate(String contractEndDate) {
        this.contractEndDate = contractEndDate;
    }
}